name: Deploy to DockerHub

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - After auto-tag

jobs:
  deploy-docker:
    name: Build and push Docker image
    if: github.repository == 'AdGuardSoftwareLimited/trusttunnel-endpoint'
    environment: release-dockerhub
    runs-on:
      - ephemeral
      - ephemeral-linux
      - ${{ vars.BUILD_IMAGE_VERSION_CORELIBS_BUILDER }}
      - ephemeral-limit-memory-8192
      - ephemeral-limit-cpu-6
      - ephemeral-limit-disk-gb-70
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Retrieve DockerHub credentials from Vault
        uses: hashicorp/vault-action@v4
        with:
          url: ${{ vars.VAULT_URL }}
          method: jwt
          role: trusttunnel-dockerhub
          secrets: |
            secret/data/ci-secrets/trusttunnel-dockerhub username | DOCKERHUB_USERNAME ;
            secret/data/ci-secrets/trusttunnel-dockerhub token | DOCKERHUB_TOKEN

      - name: Detect version
        id: version
        run: |
          VERSION=$(grep '^version = ' endpoint/Cargo.toml | head -1 | sed -e 's/version = "\(.*\)"/\1/')
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          set -e -x
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          docker buildx create --name trusttunnel-builder --use || docker buildx use trusttunnel-builder
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.prebuilt \
            --build-arg "TT_VERSION=${VERSION}" \
            -t "trusttunnel/trusttunnel-endpoint:v${VERSION}" \
            -t "trusttunnel/trusttunnel-endpoint:latest" \
            --push .
